name: E2E Tests (Docker Compose + Selenium)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    services:
      
      docker:
        image: docker:dind
        privileged: true
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      
      - name: Install Chrome and WebDriver
        run: |
          apt-get update
          apt-get install -y wget gnupg curl unzip jq
          
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main" > /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable
          
          
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+.\d+.\d+')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*})
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chromedriver/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Start Docker daemon
        run: service docker start

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Build and start infrastructure
        
        run: |
          docker compose up -d --build --wait

      - name: Wait for application to be ready via HTTP
        
        run: |
          for i in {1..30}; do
            if curl -f -s http://localhost:8080; then
              echo "Application is healthy!"
              break
            fi
            sleep 2
          done
          if ! curl -f -s http://localhost:8080; then
            echo "Application failed to start. Dumping logs:"
            docker compose logs aqa-shop
            exit 1
          fi

      - name: Run Pytest
        env:
          BASE_URL: http://localhost:8080
          DB_HOST: db
          DB_PORT: 3306
          DB_NAME: aqa_shop_db
          DB_USER: user
          DB_PASSWORD: password
        run: |
          pytest --alluredir=allure-results -n auto

      - name: Generate Allure Report
        if: always()
        continue-on-error: true
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results & Screenshots
          path: |
            allure-report/
            *.png