services:
  
  db:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aqa_shop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  
  gate-simulator:
    image: node:18-alpine
    entrypoint: ['sh', '-c']
    args:
      - |
        cd /app && npm install && npm start
    volumes:
      - ${{ github.workspace }}/gate-simulator:/app
    ports:
      - 9999:9999
    depends_on:
      - db

  
  app:
    image: openjdk:17-jdk-slim
    working_dir: /app
    entrypoint: ['java', '-jar', './aqa-shop.jar']
    volumes:
      - ${{ github.workspace }}/aqa-shop.jar:/app/aqa-shop.jar:ro
    ports:
      - 8080:8080
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PAYMENT_GATE_URL: http://gate-simulator:9999/payment
      SPRING_CREDIT_GATE_URL: http://gate-simulator:9999/credit
    depends_on:
      - db
      - gate-simulator